[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
bonding_curve = "HTiVXCCFAUsTeXGQvdx5RPEPbgxRuLXo13QtTrmzaGz1"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
