ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - bigint-buffer
  - blake-hash
  - bufferutil
  - keccak
  - msw
  - protobufjs
  - secp256k1
  - sharp
  - tiny-secp256k1
  - usb
  - utf-8-validate
